BASE_MODEL_FEATURES=['e_magic',
 'e_cblp',
 'e_cp',
 'e_crlc',
 'e_cparhdr',
 'e_minalloc',
 'e_maxalloc',
 'e_ss',
 'e_sp',
 'e_csum',
 'e_ip',
 'e_cs',
 'e_lfarlc',
 'e_ovno',
 'e_oemid',
 'e_oeminfo',
 'e_lfanew',
 'Machine',
 'NumberOfSections',
 'TimeDateStamp',
 'PointerToSymbolTable',
 'NumberOfSymbols',
 'SizeOfOptionalHeader',
 'Characteristics',
 'Magic',
 'MajorLinkerVersion',
 'MinorLinkerVersion',
 'SizeOfCode',
 'SizeOfInitializedData',
 'SizeOfUninitializedData',
 'AddressOfEntryPoint',
 'BaseOfCode',
 'ImageBase',
 'SectionAlignment',
 'FileAlignment',
 'MajorOperatingSystemVersion',
 'MinorOperatingSystemVersion',
 'MajorImageVersion',
 'MinorImageVersion',
 'MajorSubsystemVersion',
 'MinorSubsystemVersion',
 'SizeOfHeaders',
 'CheckSum',
 'SizeOfImage',
 'Subsystem',
 'DllCharacteristics',
 'SizeOfStackReserve',
 'SizeOfStackCommit',
 'SizeOfHeapReserve',
 'SizeOfHeapCommit',
 'LoaderFlags',
 'NumberOfRvaAndSizes',
 'SuspiciousImportFunctions',
 'SuspiciousNameSection',
 'SectionsLength',
 'SectionMinEntropy',
 'SectionMaxEntropy',
 'SectionMinRawsize',
 'SectionMaxRawsize',
 'SectionMinVirtualsize',
 'SectionMaxVirtualsize',
 'SectionMaxPhysical',
 'SectionMinPhysical',
 'SectionMaxVirtual',
 'SectionMinVirtual',
 'SectionMaxPointerData',
 'SectionMinPointerData',
 'SectionMaxChar',
 'SectionMainChar',
 'DirectoryEntryImport',
 'DirectoryEntryImportSize',
 'DirectoryEntryExport',
 'ImageDirectoryEntryExport',
 'ImageDirectoryEntryImport',
 'ImageDirectoryEntryResource',
 'ImageDirectoryEntryException',
 'ImageDirectoryEntrySecurity']

PE_HEADER_FEATURES=[
        'e_magic', 'e_cblp', 'e_cp', 'e_crlc', 'e_cparhdr',
        'e_minalloc', 'e_maxalloc', 'e_ss', 'e_sp', 'e_csum', 'e_ip', 'e_cs',
        'e_lfarlc', 'e_ovno', 'e_oemid', 'e_oeminfo', 'e_lfanew', 'Machine',
        'NumberOfSections', 'TimeDateStamp', 'PointerToSymbolTable', 'NumberOfSymbols',
        'SizeOfOptionalHeader', 'Characteristics', 'Magic', 'MajorLinkerVersion',
        'MinorLinkerVersion', 'SizeOfCode', 'SizeOfInitializedData', 'SizeOfUninitializedData',
        'AddressOfEntryPoint', 'BaseOfCode', 'ImageBase', 'SectionAlignment', 'FileAlignment',
        'MajorOperatingSystemVersion', 'MinorOperatingSystemVersion', 'MajorImageVersion',
        'MinorImageVersion', 'MajorSubsystemVersion', 'MinorSubsystemVersion', 'Reserved1',
        'SizeOfImage', 'SizeOfHeaders', 'CheckSum', 'Subsystem', 'DllCharacteristics',
        'SizeOfStackReserve', 'SizeOfHeapReserve', 'SizeOfHeapCommit', 'LoaderFlags',
        'NumberOfRvaAndSizes'
    ]

PE_SECTION_FEATURES=[
        'text_Misc_VirtualSize', 'text_VirtualAddress',
        'text_SizeOfRawData', 'text_PointerToRawData', 'text_PointerToRelocations',
        'text_PointerToLinenumbers', 'text_NumberOfRelocations', 'text_NumberOfLinenumbers',
        'text_Characteristics', 'data_Misc_VirtualSize', 'data_VirtualAddress',
        'data_SizeOfRawData', 'data_PointerToRawData', 'data_PointerToRelocations',
        'data_PointerToLinenumbers', 'data_NumberOfRelocations', 'data_NumberOfLinenumbers',
        'data_Characteristics', 'rdata_Misc_VirtualSize', 'rdata_VirtualAddress',
        'rdata_SizeOfRawData', 'rdata_PointerToRawData', 'rdata_PointerToRelocations',
        'rdata_PointerToLinenumbers', 'rdata_NumberOfRelocations', 'rdata_NumberOfLinenumbers',
        'rdata_Characteristics', 'bss_Misc_VirtualSize', 'bss_VirtualAddress',
        'bss_SizeOfRawData', 'bss_PointerToRawData', 'bss_PointerToRelocations',
        'bss_PointerToLinenumbers', 'bss_NumberOfRelocations', 'bss_NumberOfLinenumbers',
        'bss_Characteristics', 'idata_Misc_VirtualSize', 'idata_VirtualAddress',
        'idata_SizeOfRawData', 'idata_PointerToRawData', 'idata_PointerToRelocations',
        'idata_PointerToLinenumbers', 'idata_NumberOfRelocations', 'idata_NumberOfLinenumbers',
        'idata_Characteristics', 'edata_Misc_VirtualSize', 'edata_VirtualAddress',
        'edata_SizeOfRawData', 'edata_PointerToRawData', 'edata_PointerToRelocations',
        'edata_PointerToLinenumbers', 'edata_NumberOfRelocations', 'edata_NumberOfLinenumbers',
        'edata_Characteristics', 'rsrc_Misc_VirtualSize', 'rsrc_VirtualAddress',
        'rsrc_SizeOfRawData', 'rsrc_PointerToRawData', 'rsrc_PointerToRelocations',
        'rsrc_PointerToLinenumbers', 'rsrc_NumberOfRelocations', 'rsrc_NumberOfLinenumbers',
        'rsrc_Characteristics', 'reloc_Misc_VirtualSize', 'reloc_VirtualAddress',
        'reloc_SizeOfRawData', 'reloc_PointerToRawData', 'reloc_PointerToRelocations',
        'reloc_PointerToLinenumbers', 'reloc_NumberOfRelocations', 'reloc_NumberOfLinenumbers',
        'reloc_Characteristics', 'tls_Misc_VirtualSize', 'tls_VirtualAddress',
        'tls_SizeOfRawData', 'tls_PointerToRawData', 'tls_PointerToRelocations',
        'tls_PointerToLinenumbers', 'tls_NumberOfRelocations', 'tls_NumberOfLinenumbers',
        'tls_Characteristics', 'pdata_Misc_VirtualSize', 'pdata_VirtualAddress',
        'pdata_SizeOfRawData', 'pdata_PointerToRawData', 'pdata_PointerToRelocations',
        'pdata_PointerToLinenumbers', 'pdata_NumberOfRelocations', 'pdata_NumberOfLinenumbers',
        'pdata_Characteristics'
    ]

# only top N important features to be selected
DLL_IMPORTED_FEATURES=[]

# only top N important features to be selected
API_FUNCTION_FEATURES=[]